### ISSUE TITLE
ServiceWorker to "service worker" mapping and stability

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#622] opened 2015-02-13 19:48 UTC
Stumbled upon this while running blink wpt tests. The spec doesn't define anything, maybe I'm just missing some obvious knowledge. Specific example is the test service-workers/active.html (console.log additions are mine):

          .then(step(function(f) {
          frame = f;
          return navigator.serviceWorker.register(url, {scope: scope});
        }))
      .then(step(function(r) {
          registration = r;
          console.log(r.installing.state);
          r.installing.addEventListener('statechange', function() {
            console.log("State changed to " , r.installing.state);
          });
          return wait_for_state(t, r.installing, 'activating');
        }))

Here r.installing is valid in the promise handler, but inside the event listener, there is no reason r.installing has to be valid in the current spec. In the first statechange the spec says to set the 'waiting worker to the installing worker' then 'set installing worker to null', then 'update waiting worker's state to installed' and so on. The same switch happens of waiting -> active, waiting = null, when the worker finishes activation. When this happens, Gecko will immediately (not violating JS run to completion, but noticable in event handlers) invalidate installing and set waiting. With nothing specified, I assume that when the spec says to set waiting to something, that is also immediately reflected in the per-global JS exposed 'waiting'. In such a case the wait_for_state() function does not track these attribute changes correctly. If Blink passes the test, it may be shipping an incompatible implementation.

cc/ @mattto

**Comment by nikhilm** [comment] 2015-02-13 19:49
@jgraham

**Comment by mattto** [comment] 2015-02-14 00:51
I agree with your interpretation of the spec. If r.installing is not null in the statechange event for 'installed', I think that's a Blink bug.

**Comment by KenjiBaheux** [comment] 2015-02-17 03:08
@mattto can you file a bug in crbug and add a link here? Thanks.

**Comment by mattto** [comment] 2015-02-18 02:49
Tracked at https://code.google.com/p/chromium/issues/detail?id=459457

**Comment by mattto** [comment] 2015-02-18 14:23
@nikhilm I'm not able to repro the behavior you report on a recent build. However, I found a similar issue. 
In the statechange for 'installed', r.installing is null but r.waiting's state is 'installing'.

The reason is that Blink can mint multiple ServiceWorker JS objects representing the same Service Worker. Therefore one JS object can have its state modified and the statechange event dispatched before another one representing the same worker gets the state modification. I believe this is a spec violation, because Update State first sets state on the "worker" before dispatching the event to each of the JS objects. Do you agree, and does Firefox do it correctly?

Here is my test case:
```javascript
promise_test(function(t) {
    var scope = 'resources/state/';
    var registration;
    var sw;

    return navigator.serviceWorker.register('resources/empty-worker.js', { scope: scope })
      .then(function(r) {
          sw = r.installing;
          return new Promise(function(resolve) {
              r.installing.addEventListener('statechange', function(e) {
                  if (e.target.state != 'installed')
                    return;
                  // These pass on Blink.
                  assert_equals(r.installing, null);
                  assert_equals(r.waiting.scriptURL, sw.scriptURL);
                  assert_equals(r.active, null);
                 // This fails on Blink, it's still 'installing'.
                 assert_equals(r.waiting.state, 'installed');
                  resolve();
                });
            });
        });
  }, 'statechange');
```

**Comment by mattto** [comment] 2015-04-03 02:03
@nikhilm FYI I believe the problem I described above is fixed as of http://crbug.com/459457, though I was never able to reproduce the original bug you reported.

**Closed** 2015-10-28 08:23 UTC
