### ISSUE TITLE
Update algorithm and redirects

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#618] opened 2015-02-10 08:08 UTC
I don't understand why this section checks "redirect count". That is a bookkeeping detail of the Fetch specification and is not for other specifications.

If somebody could explain the intent I can maybe say what we should do instead.

**Comment by annevk** [comment] 2015-02-10 15:36
This issue is blocking Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1131271

**Comment by jungkees** [comment] 2015-02-11 07:25
I'm also looking up the history. If a redirection were considered as a security error, it shouldn't have been succeeded at all. 

/cc @slightlyoff @jakearchibald

**Comment by annevk** [comment] 2015-02-11 07:43
Yeah, but if you want to block redirects you should not be checking "redirect count". Instead you should set the manual redirect flag and check the status code of the response (likely require it to be in range 200 to 299).

**Comment by jungkees** [comment] 2015-02-11 07:59
Alright. Depending on the decision, I'll update it as commented. A question is, shouldn't the response code be one of 301/302/303/307/308 when the manual redirect flag is set?

**Comment by annevk** [comment] 2015-02-11 08:05
I don't understand the question.

**Comment by jungkees** [comment] 2015-02-11 08:21
I mean, "Shouldn't the response code be one of 301/302/303/307/308  in order to consider it a security (redirection) error"? With "likely require it to be in range 200 to 299" in your comment above, did you mean responses with those status code are NOT security error?

**Comment by annevk** [comment] 2015-02-11 08:40
I mean we should only respect those response code if we are not going to handle redirects.

**Comment by jungkees** [comment] 2015-02-12 05:15
Discussed with @slightlyoff and concluded preventing redirection is the safe thing to do here. Updated the text as such: 4f3a555ae450128182330bac67055288fdf5fe70. @annevk please review.

**Comment by annevk** [comment] 2015-02-12 08:08
Could you please share the rationale? Why do you reject with a `"NetworkError"` while `fetch()` rejects with a `TypeError`?

**Comment by jungkees** [comment] 2015-02-12 08:21
I thought it was a right DOMException as fetch pertains to network operation. Happy to align it to fetch. Is there any general guideline when to use simple exception (TypeError) and when to use DOMException?

**Comment by jungkees** [comment] 2015-02-12 08:43
If you asked about the rationale why we'd want to prevent redirection, we thought it'd be part of not allowing x-origin SWs.

**Comment by annevk** [comment] 2015-02-12 09:35
You can prevent that by setting the fetch mode to same-origin, no?

**Comment by annevk** [comment] 2015-02-12 09:36
(I don't think we have guidelines on exceptions.)

**Comment by jakearchibald** [comment] 2015-02-12 10:57
If we want to allow redirects for the SW script, there's a few questions we need to answer:

1. If the registration's script url is `/foo.js`, and during an update it hits a redirect to '/bar.js', which url will be used for the next update check? Do redirects update the script url on the registration object?
2. If the scope is `/foo/` and the script url is `/foo/bar.js`, but redirects to `/foo/scripts/bar.js`, should that work?
3. If the scope is '/foo/' and the script url is `/foo/scripts/bar.js`, but redirects to `/foo/bar.js`, should that work?

I think 'no' for all three.

**Comment by annevk** [comment] 2015-02-12 11:00
I would expect yes for 1 and the others explain why introducing scopes just for service workers is a hack. :-(

**Comment by jakearchibald** [comment] 2015-02-12 11:25
The reason I say no for 1 is because you're otherwise likely to introduce thrashing.

1. registration's script url is `/foo.js`
1. update happens, redirect hit, registration's script url is `/bar.js`
1. page refreshes, encounters `.register('/foo.js'), registration's script url is back to `/foo.js`, this triggers a fetch of `/foo.js` because the registration has changed as a result of the register call

2 & 3 aren't solved by dropping scopes, the problem is caused by catering to sites that thinking giving someone webspace in a directory sandboxes them to that director.

**Comment by annevk** [comment] 2015-02-12 13:00
If `/foo.js` is fetched it will redirect as well so I'm not sure why the script URL would be `/foo.js`.

**Comment by jungkees** [comment] 2015-02-13 02:12
As the script URL passed to `.register` was `/foo.js` again while registration's workers' script URL had been set to `/bar.js` in the previous register, this new register request would not resolve with the existing registration but rather trigger new update every time.

> Why do you reject with a "NetworkError" while fetch() rejects with a TypeError?

e9fabe32d10ed8f2fbf1bdea481ef9e47d550bd4

**Comment by annevk** [comment] 2015-02-18 13:37
So this is all done now, correct? That is, we gave up on redirects due to the design of the `register()` API.

**Comment by annevk** [comment] 2015-02-18 13:40
Where is the issue about setting request's client to null?

**Comment by jungkees** [comment] 2015-02-23 07:20
> So this is all done now, correct? That is, we gave up on redirects due to the design of the register() API.

Yes.

> Where is the issue about setting request's client to null?

This is the one: https://github.com/slightlyoff/ServiceWorker/issues/615.

**Comment by jungkees** [comment] 2015-02-23 07:26
So let me close this issue. The issue about setting request's client to null is tracked in #615, and pointed by from Soft Update algorithm in the spec: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#soft-update-algorithm.

**Closed by jungkees** 2015-02-23 07:26 UTC
