### ISSUE TITLE
Take into accounts etags on initialization importScripts responses to update the Service Worker

### ISSUE THREAD

**Issue by delapuente** [slightlyoff/ServiceWorker#830] opened 2016-02-09 14:46 UTC
For developers, composition of diverse service worker functionality can be done via `importScripts()`. The problem with this approach is that is needed to byte-alter the sw in order to get it updated. If not, imported scripts could change but the main file could remain the same. Traditional solutions forces the developer to manually add some kind of change in the sw file but the specification could take into account [eTag header](https://en.wikipedia.org/wiki/HTTP_ETag) to determine if imported scripts have changed. If the eTag is not present, it can default to the current behaviour.

This way, even if the sw itself has not changed, a byte-level change in one of the eTag will trigger the update.

**Comment by jakearchibald** [comment] 2016-04-10 18:20
Dupe of https://github.com/slightlyoff/ServiceWorker/issues/839?

**Closed by jakearchibald** 2016-04-10 18:20 UTC
