### ISSUE TITLE
There should be no such thing as "fail to activate"

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#659] opened 2015-03-24 03:48 UTC
Consider the Service Worker

```javascript
skipWaiting();
onactivate = function(e) {
  e.waitUntil(clients.claim()
    .then(function() {
      return Promise.reject();
    })
  );
};
```

As per spec, the registration will have no active worker, the worker will be in redundant state, yet it may still be the controller of clients. Probably Activate step 15 "If activateFailed is true" should also relinquish the worker's controllees.

**Comment by jungkees** [comment] 2015-03-24 10:33
That makes sense. Otherwise, Handle Fetch will try to use that client's active worker's containing registration (whose active worker has been effectively set to null already) to fire `fetch`.

Addressed: b4ad5e9014158abe2cb85e34abc2e4b30e62b2cf. Thanks.

**Comment by jakearchibald** [comment] 2015-03-24 13:28
Hmm, I thought we'd decided that a ServiceWorker that fails to activate is still active (in fact, it's active at the start of activation).

The problem is the activation could have half-applied, leaving some data stores migrated and others not, so rolling back is likely to leave things just as boken. Unregistering is bad because you'll lose push registrations etc. I thought we were going to leave this as an exercise for the developer?

Is the current pattern to leave the registration with a null active state? When would it next pick up an update? (was there a discussion around this I missed?)

**Comment by mattto** [comment] 2015-03-25 01:00
The current spec makes the SW the "active" worker immediately when activation begins, but it doesn't get any events until it becomes "activated". If activation fails, the registration is left with a null active worker. Chrome additionally unregisters the registration if it has no workers, although that might be a implementation bug.

**Comment by jungkees** [comment] 2015-03-25 02:20
> Is the current pattern to leave the registration with a null active state? When would it next pick up an update? (was there a discussion around this I missed?)

Yes, it is, and the next update would be triggered by one of `navigator.serviceWorker.register()`, `registration.update()` from clients or Soft Update by the user agent.

As you pointed, if it'd failed with the activation, there's a chance the storage state would have been broken. So I guess it's fair to make the service worker's state redundant to notify the activation failure. And as such the subsequent functional events should not be dispatched to this service worker until it gets recovered.

> The current spec makes the SW the "active" worker immediately when activation begins, but it doesn't get any events until it becomes "activated".

Right. So if we leave this an `activating` state, it won't serve any events until developer fix this.

> Chrome additionally unregisters the registration if it has no workers, although that might be a implementation bug.

As @jakearchibald said, "Unregistering is bad because you'll lose push registrations etc.". 

We're currently somewhat aggressively sweeping those registrations (having no worker) out during the Update/Install steps. I think it'd be still fine to unregister them when a network error (bad request or script fetch error) or a security error (path or MIME type error) occurs, but we can probably exclude the script execution error cases.

**Comment by mattto** [comment] 2015-03-25 06:23
Technically, I don't think the service worker can be "recovered" once it reaches redundant state, what would happen is another service worker (with possibly the same script) would be installed and activated.

Anyway, what is left to do here? I don't recall the details of the decision to make the worker that fails to activate still the active worker, and I'm not sure whether the current spec is aligned with that decision...

Chrome has a crash bug if you fail activation after claiming, so I'm planning to fix that as per the current spec (as of b4ad5e9): the worker will relinquish its controllees upon activation fail, and will track the spec as we go.

Also, it seems right to fire "controllerchanged" in this case, no?

**Comment by jungkees** [comment] 2015-03-25 07:05
> Technically, I don't think the service worker can be "recovered" once it reaches redundant state

By "recovered", I just meant a new registration/update attempt.

> I don't recall the details of the decision to make the worker that fails to activate still the active worker

I don't recall them either. It'd been spec'ed to make the worker redundant and set the active worker to null.

> Also, it seems right to fire "controllerchanged" in this case, no?

Agreed. I'll address this.

**Comment by jungkees** [comment] 2015-03-26 06:01
> Also, it seems right to fire "controllerchanged" in this case, no?

Addressed: 20e4861342d5c21133c9906569449c5e8d588534.

**Comment by mattto** [comment] 2015-03-30 09:22
Clarification question: Inside the controllerchanged event handler, should getRegistration().then(r.active) be null, the redundant worker, or is it unspecified? The spec sets active worker to null after running Update State and Notifiy Controller Change, but those algorithms queue a task (on separate event loops), so IIUC things could happen in any order.

**Comment by jakearchibald** [comment] 2015-03-30 18:18
As a developer, I'd except `r.active` to be null if there's no worker to send events like `fetch` to.

I'd been against having registrations with no workers in the past, but I'm coming around to this idea. Here are the issues:

**We keep trying to install/activate the same worker** each time `navigator.serviceWorker.register` is called, even if the script hasn't changed. This is because we've thrown away the broken worker so we can't do a byte-for-byte check. This could be fixed by retaining the broken worker internally for checking.

**This makes things difficult for other specs** such as the [push API](https://w3c.github.io/push-api/#the-push-event). Right now they can assume there will always be an active worker to fire events in, as they require an active worker to set up push registration. I'm not sure what the best way to fix this is, I guess they'll have to manage their own queuing or simply drop push messages while the SW is broken.

**Only .register can trigger a retry**. This isn't a problem now, but I think we want the `push` event (and maybe others) to be able to trigger soft updates. This is because sites may use another origin for push management, than the origin users are likely to visit frequently. Eg, if a site has multiple international sites, they may pick one for `push`, if a site cannot yet fully switch to `https`, they may use a small `https` origin for user profile & push. The answer here is to remove step 5 of [soft update](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#soft-update-algorithm), but I don't remember if there was a good reason we make that check.

**Comment by mattto** [comment] 2015-03-31 06:43
> As a developer, I'd except r.active to be null if there's no worker to send events like fetch to.

Agreed, Chrome will first set r.active to null then dispatch the 'controllerchange' event. Note however (just in case it's not clear) that r.active can be an "activating" SW, which would not receive these events until activation succeeds.

There's weirdness about the naming 'controllerchange'. It's fired when your registration's .active changes, but that doesn't mean your .controller changed. Should it be renamed?

**Comment by mattto** [comment] 2015-03-31 06:59
Sorry, please disregard the second part of my last comment. However, there is a related spec bug: Activate's step 10: "For each service worker client client whose active worker is not null..." seems wrong. It should say "for clients already associated with the registration..." Reading that is what caused me to think the controllerchange naming is wrong.

**Comment by jungkees** [comment] 2015-03-31 08:48
> however (just in case it's not clear) that r.active can be an "activating" SW, which would not receive these events until activation succeeds.

`controllerchange` events' target is ServiceWorkerContainer objects. So, it doesn't have to do with the worker's state I guess?

> Activate's step 10: "For each service worker client client whose active worker is not null..." seems wrong. It should say "for clients already associated with the registration..." Reading that is what caused me to think the controllerchange naming is wrong.

The state where client's active worker is not null means the client is currently being controlled. So I think the two in your comment above have the same meaning.

**Comment by jakearchibald** [comment] 2015-03-31 09:00
Added another concern to https://github.com/slightlyoff/ServiceWorker/issues/659#issuecomment-87778808

**Comment by jungkees** [comment] 2015-03-31 09:11
> Activate's step 10: "For each service worker client client whose active worker is not null..." seems wrong.

Clarified this with @mattto in IRC. Fixed: b0eed1a18b5b1ac37fa9b7ea943e7a99ec03a51c.

**Comment by jakearchibald** [comment] 2015-03-31 11:50
Added another concern to https://github.com/slightlyoff/ServiceWorker/issues/659#issuecomment-87778808 - starting to worry a bit about the complexity this introduces.

**Comment by mattto** [comment] 2015-04-02 07:40
Tracked in Blink: https://code.google.com/p/chromium/issues/detail?id=471616

**Comment by jungkees** [comment] 2015-04-10 08:21
Re https://github.com/slightlyoff/ServiceWorker/issues/659#issuecomment-87778808, here's some investigation about what we do with a registration. (http://slightlyoff.github.io/ServiceWorker/spec/service_worker/sw-registration-figure.svg.)

**[Create Registration]** A registration is created only by `navigator.serviceWorker.register()`.

**[Update Registration]** The state of the registration can be mutated by:
  - `navigator.serviceWorker.register()`
  - `registration.update()`
  - Soft Update (This can be called by UA internal context and other APIs such as Push API.)

**[Delete Registration]** The registration can be deleted by:
  - `registration.unregister()`
  - Handle Service Worker Client Unload (when there's no other client left and the uninstalling flag is set.)
  - **Errors in Update**
  - **Errors in Install**

The first two points in **[Delete Registration]** are explicit, so we may want to check the rest of the points. Here's **the list of errors triggering Clear Registration from Update**:
  - Request constructor (to prepare fetching script) throws
  - Network error by detecting a redirect
  - Script's MIME type mismatch
  - `Service-Worker-Allowed` header parsing failure
  - Script's location violation
  - An uncaught runtime script error when run a worker with the fetched script

**The list of errors triggering Clear Registration from Install**:
  - An uncaught runtime error in the oninstall event listener
  - Install failure detected by the rejection of waitUntil promise

IMO, these errors are mostly something devs need to fix during the development/deployment. (Those can be fixed by the next Update attempt.) In the case of the registration which should be permanently removed, an explicit call to `registration.unregister()` seems reasonable. Also as @jakearchibald pointed out, the registration through the corresponding ServiceWorkerRegistration object is bound to PushManager, SyncManager, GeofenceManager, etc.

Are there other concerns that I missed?

**Comment by jungkees** [comment] 2015-04-10 09:51
> We keep trying to install/activate the same worker each time navigator.serviceWorker.register is called, even if the script hasn't changed.

In the case the registration already has an active worker, `.register()` will return in the step 4.2.2.1 of Register. But when it has a waiting worker/an installing worker, `.register()` will get through to install/activate each time. I agree retaining the registration on error will solve this.

> This makes things difficult for other specs to know when they can fire events such as the push API. 

In the case of fetch, it falls back to network request (we may regard it as the default behavior.) For Push API, there's any expected behavior discussed to date?

> Only .register can trigger a retry.

I suppose we thought that an update for a registration with no worker has no meaning back then. In the case we allow a registration with no worker, I agree this step should be removed.

> If the next worker fails to install, we lose the registration, due to 7.3.3.1 of Install. This means going offline during an update would lose the user's push subscriptions etc.

That scenario is bad, but the current steps have a guard to check whether there was any worker in the registration. So, for instance, if push once successfully subscribed, that associated service worker registration should have an active worker which prevents this registration is deleted when an installation fails.

> Other specs need to deal with queued events losing their associated worker.

Currently, Handle Fetch waits until the activation completes before queuing the task, and in the case it fails it falls back to a network request (the default behavior. See [Handle Fetch](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#on-fetch-request-algorithm) step 15.)

For other functional events, they are guided to invoke [Handle Functional Event](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#handle-functional-event-algorithm) which queues a task to call the callbackStep given by those specific APIs. So, one possibility is Handle Functional Event returns some kind of error to the caller when the activation fails so the caller can handle the error with its own default behavior. I'm curious to know what Push and BackgroudSync expect.

/cc @johnmellor @mvano @jkarlin

**Comment by mattto** [comment] 2015-04-13 09:10
This bug seems about two things: one is whether a version that failed to activate should relinquish controllers, and one is whether a registration with no workers can exist. For Blink...

The "relinquish controllees" bit was fixed in https://code.google.com/p/chromium/issues/detail?id=471616

The "registration with no workers" bit is tracked in https://code.google.com/p/chromium/issues/detail?id=476456

**Comment by slightlyoff** [comment] 2015-04-14 19:31
I don't think there's a valid concept of "fail to activate". Once you're activating, you're committed. Nothing more to be done.

**Comment by mattto** [comment] 2015-04-16 09:17
@slightlyoff I think the problem is there's a difference between activating and activated: the current spec blocks navigation until the activating worker becomes activated. If the worker "failed to activate" (called waitUntil(rejected)), should we continue to block or do something else like bypass the worker? Or maybe even say waitUntil(rejected) means the same as waitUntil(resolved)... the worker becomes activated?

**Comment by jakearchibald** [comment] 2015-04-22 15:53
> Or maybe even say waitUntil(rejected) means the same as waitUntil(resolved)... the worker becomes activated?

This is what we decided 100 years ago when we met in SF. I'm open to better models, but having a registration without any workers seems to open up a whole load of problems.

**Comment by mattto** [comment] 2015-04-23 01:26
SGTM, that will actually simplify our code a bit. I'll update Chrome if there's agreement and spec here.

**Comment by jungkees** [comment] 2015-04-23 06:24
Yeah, so we have no activation failure concept. It was so as dealt with in https://github.com/slightlyoff/ServiceWorker/issues/115#issuecomment-50316488. I might have missed it. The Activate algorithm still had had the failure handling steps by then. (and to date actually.)

So, I'll remove the activation failure handling steps in Activate algorithm for `e.waitUntil(rejected)`.

Wants to check if I'm on the same page: the uncaught runtime script error in the `onactive` event listener and the termination of the activating worker before the waitUntil promise settles will not be treated as an activation failure, either. So, we just let it remain the _active worker_ and change its state to _activated_.

**Comment by mattto** [comment] 2015-04-23 07:12
>  the uncaught runtime script error in the onactive event listener and the termination of the activating
> worker before the waitUntil promise settles will not be treated as an activation failure, either. 

I believe that's right, there's no such thing as activation failure at all. Once the waitUntil promise is settled or UA times it out, the worker is activated. That's what will simplify our code :)

**Comment by jungkees** [comment] 2015-04-23 08:20
> remove the activation failure handling steps in Activate algorithm

Addressed: 71c4308da71f35c91bbce4a491430f65d5aa100a.

**Comment by jungkees** [comment] 2015-04-23 08:26
> having a registration without any workers seems to open up a whole load of problems.

By removing the concept of the activation failure, it seems once a registration acquires an active worker that registration will live until it's explicitly unregistered.

**Comment by jakearchibald** [comment] 2015-04-23 16:35
lgtm

**Comment by mattto** [comment] 2015-04-24 03:13
Tracked in http://crbug.com/480050

**Comment by jungkees** [comment] 2015-05-08 06:52
Closing.

**Closed by jungkees** 2015-05-08 06:52 UTC

**Comment by flaki** [comment] 2015-05-17 08:58
Tracked in http://bugzil.la/1163412

**Comment by brettz9** [comment] 2018-04-27 09:34
This may be more of a support question, but it seems relevant to the question here (and whether workarounds need to be better documented).

[This Google Developer's page](https://developers.google.com/web/ilt/pwa/live-data-in-the-service-worker#service-workerjs) suggests putting database upgrades within the `activate` handler, but it seems that an inability for `activate` to fail means that one cannot leverage say an IndexedDB upgrade transaction rejecting upon failure so that the upgrade may be tried again automatically at some point or through some `triggerActivate()` mechanism.

Or, as in my case, passing in a message to the `activate` handler--as to indicate which files of my library users to store into IndexedDB for them--becomes problematic: if my file sending the message was no longer present, the `activate` phase would fail without me having any apparent way to trigger an update.

It seems to me that the only solution is either to handle IndexedDB upgrades outside of the service worker (probably the easiest solution), or to I guess unregister and register again.

**Comment by brettz9** [comment] 2018-04-27 10:34
Thanks, I do see that the promise could be extended to try as much again (assuming a timeout doesn't win out). But what of the issue with messaging from the app into the worker (before a timeout stops it)?

I am currently passing in info from my library users' files (already cached during `install`) which I am reading into IndexedDB during the activation phase, but if the user closes their tabs, e.g., during the waiting phase, there may be no other code of mine left running which can pass in the dependency file info so that the activation in the worker can complete so that it is available next time the user loads my site.

And the impression I get is that I can't store this in a variable during the install phase such that it will be available during the activation. Would I have to create a separate database to share this state persistently?

**Comment by wanderview** [comment] 2018-04-27 13:39
You can call `unregister()` from the activate event if you have a non-recoverable error and want to get an install event again.  It may be a bit sketchy if there is already a controlled client, though.
