### ISSUE TITLE
Clients & postMessage

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#609] opened 2015-01-20 18:25 UTC
A client can message a particular ServiceWorker via:

```js
navigator.serviceWorker.controller.postMessage("Hello");
```

I guess `messageEvent.source` would be a client, but where `client.postMessage` goes isn't properly defined. This is also a problem for clients created by `clients.getAll`.

In my ignorance, I thought `client.postMessage` would go to `global.onmessage`, but `SharedWorker` doesn't have that, and I hadn't really appreciated that `window.onmessage` was only for window-to-window communication.

So yeah, if a ServiceWorker sends a client a message, where does it land?

We could have `navigator.serviceWorker.onmessage` as the target for messages from a SW to this specific client, where `messageEvent.source` is an instance of `ServiceWorker`, allowing state inspection & `postMessage` back.

**Comment by jakearchibald** [comment] 2015-01-20 18:34
@mvano @johnmellor @beverloo @mounirlamouri - in case you care from a push point of view

**Comment by annevk** [comment] 2015-01-21 08:15
I think on both sides we want the `postMessage()` method and `onmessage` event handler to reside on the same object. That symmetry has been maintained for all message channel solutions to date.

That puts into question whether `Client` should be a snapshot object at all.

**Comment by jakearchibald** [comment] 2015-01-21 15:21
I don't think the snapshot nature of `Client` is an issue here. Windows & workers have no access to the client object, so they can't listen to its message events.

The client is a static representation of the window/sharedworker/dedicatedworker. Client exists because `WindowProxy` can't be used for obvious reasons, that's why I thought `window.onmessage` made sense as a message destination.

Now that `getAll()` only returns window clients by default, we could have `getAll({type: 'all'})` return a mix of `WindowClient`, `DedicatedWorker` & `SharedWorker`. `WindowClient` would `postMessage` to `window.onmessage`, because it's a worker-safe `WindowProxy`.

**Comment by annevk** [comment] 2015-01-21 18:08
The problem is that if `Client` is the place from which you message towards client, it should also be the place from which you receive messages from the client. Similar to `ServiceWorkerRegistration` being the proposed place to send messages towards the service worker and receiving messages from the service worker.

(Having `getAll()` not actually return all by default is confusing. Name it `get()` then.)

**Comment by annevk** [comment] 2015-01-22 10:41
Idea: we provide no built-in messaging API and require usage of `BroadcastChannel`. (We might still provide built-in messaging for individual fetches at a later point.)

**Comment by jakearchibald** [comment] 2015-01-22 11:37
Hah, I had the same thought. Does anyone implement `BroadcastChannel` yet?

Even with `BroadcastChannel`, there's going to be asymmetry in messaging. You can use it to broadcast to multiple windows/workers, but due to the way ServiceWorker terminates when not in use, you'll need to use something like `navigator.serviceWorker.controller.postMessage` to reliably talk back.

I take it you're dead against `WindowClient` (as a worker-friendly `WindowProxy`) posting to `window.onmessage`?

**Comment by annevk** [comment] 2015-01-22 11:58
Firefox implements it.

If there's some form of buffering it could work for service workers I think although that might be somewhat tricky. (Though that needs to be solved either way.)

I'm not sure what you mean by `WindowProxy` in this context. I don't really see how `WindowClient` can work if we keep it static. And posting to the `Window` object seems odd.

**Comment by jakearchibald** [comment] 2015-01-22 12:27
> I'm not sure what you mean by `WindowProxy` in this context.

I see `WindowClient` as a worker-safe version of `WindowProxy`. It's a worker's connection to the window. That's why I thought posting to `window.onmessage` was ok.

**Comment by jakearchibald** [comment] 2015-01-27 00:58
@annevk can you sum up why having `windowClient.postMessage` proxying to the associated Window's `.postMessage` is a bad idea?

**Comment by annevk** [comment] 2015-01-27 10:23
* The expected model is that each end has a `postMessage` and `onmessage` method. Breaking that is needlessly confusing. The `postMessage` model for `Window` is legacy, pre-`MessageChannel`, confusing, and does not match well to this anyway.
* The `postMessage` model for `Window` exists, overloading it with completely orthogonal `message` events requires all existing library code to be rewritten to take into account that service workers can now also produce events there.

**Comment by jakearchibald** [comment] 2015-02-02 05:01
I disagree that the `postMessage` model we have with `Window` is confusing compared to what you end up doing with `SharedWorker`. I think "requires all existing library code to be rewritten" is an exaggeration, but `messageEvent.source` being not-a-Window is an issue.

Will arrange a call to go through this.

**Comment by annevk** [comment] 2015-02-02 09:09
I think it would make more sense for someone to sit down with @Hixie and sort this through.

**Comment by jakearchibald** [comment] 2015-02-06 11:21
@Hixie some background:

A page can `postMessage` to a ServiceWorker via:

```js
navigator.serviceWorker.controller.postMessage("Hello");
```

`navigator.serviceWorker.controller` is the ServiceWorker instance controlling the page (and likely other pages/Workers/SharedWorkers). Posted messages land in `self.onmessage` in the ServiceWorker's global scope.

In the ServiceWorker, `self.clients` gives the ServiceWorker insight into clients on the origin, where clients are Windows, Workers and SharedWorkers. The current API allows:

```js
clients.matchAll().then(clients => {
  clients[0].postMessage("Hello");
});
```

…as a method for the ServiceWorker to communicate with a client. This is where there's disagreement. My thinking was, for windows, `client.postMessage` would land in `window.onmessage`, because a window client should behave like `WindowProxy` but be safe to use in a worker. @annevk disagrees (see https://github.com/slightlyoff/ServiceWorker/issues/609#issuecomment-71622477).

It means that `messageEvent.source` within `window.onmessage` would be an instance of `ServiceWorker` if the message was sent from a ServiceWorker. If libraries depended on `messageEvent.source` being a `WindowProxy`, things could break. This would only affect sites that already use a library with that assumption, then add ServiceWorker, then `postMessage` a client running that library. This would be revealed during development rather than on a live site, and we could monitor that as the feature moves through Canary/Dev/Beta.

If the client is a SharedWorker we don't currently have anywhere to land the message. I think we should just return the Worker/SharedWorker objects as clients, and the developer can communicate with them the standard way. Basically, we only need clients for windows because there isn't currently a window representation that can exist in a worker, `WindowClient` becomes that thing.

## Other possibilities

@annevk suggests dropping `postMessage` and instead relying on `BroadcastChannel` which Mozilla recently implemented. I'm fond of `BroadcastChannel`, but it doesn't allow communication with a specific client.

There's also the idea of stashing message ports within ServiceWorker registrations https://gist.github.com/mkruisselbrink/536632fcd99d45005064 - but this comes with all the GC observation of `PortCollection`, along with potential leaks if both ports are stashed. Plus it's pretty complicated compared to `client.postMessage`.

**Comment by jakearchibald** [comment] 2015-02-12 14:38
We're still stuck here. In case it helps, here are the requirements:

* A page/worker can communicate with a specific serviceworker on the origin.
That serviceworker may be  in any state except redundant. The serviceworker may be part of any registration on the origin. The page may or may not be controlled by a serviceworker.

**Comment by jakearchibald** [comment] 2015-02-12 14:39
ffs hit comment before I was done. Ignore the above post for a moment

**Comment by annevk** [comment] 2015-02-12 16:23
A client (C) is associated with zero or more `ServiceWorker` objects. A service worker (SW) is associated with zero or more `Client` objects. These are the entities that need to be able to communicate with each other.

I think we need to reconsider making these objects live (and therefore unique per global). When live message listeners could be registered at SW and C creation time and things would work. (This would mean SW is not always woken up by an event dispatched on the global.)

Making them live would require some kind of synchronization event when a new C or SW presents itself to the other side. It would also mean that any state on `Client` and `ServiceWorker` objects should probably be behind promises if it can easily change.

User agents can still optimize by creating these collections lazily when they are accessed (or assumed to be accessed based on experience running the code).

**Comment by mattto** [comment] 2015-02-16 08:19
Blink has already shipped Client.postMessage. We plan to add a console message warning the developer that the API may change.

**Comment by jakearchibald** [comment] 2015-02-17 17:49
Update:

We're in agreement that `serviceWorkerInstance.postMessage` should land at `self.onmessage` within the ServiceWorker. The `messageEvent.source` will be an instance of `WindowClient` or `Client` depending on the sender.

`clientInstance.postMessage` will land at `navigator.serviceWorker.onmessage`. The `messageEvent.source` will be an instance of `ServiceWorker` representing the sender.

This changes what Chrome has already shipped, but it gives us a sensible place to land messages in SharedWorkers, and doesn't overload `window.onmessage`.

I don't think this can be specced in terms of ports, as it isn't 1:1 (both `onmessage` destinations can receive messages from multiple sources). The spec for [BroadcastChannel](https://html.spec.whatwg.org/multipage/comms.html#broadcasting-to-other-browsing-contexts) will be a good reference, as it does something similar, although less specific.

@jungkees do you have any time to have a go at specing this? I'm snowed under with talk-writing :(

**Comment by inexorabletash** [comment] 2015-02-17 23:24
Just to inform implementation, do we have thoughts (to pass on to @Hixie) about updating the IDL definition for `MessageEvent`'s `source`?

Currently it is `(WindowProxy or MessagePort)?`; Chrome's implementation has it as `EventTarget?` and we were planning to do something hacky until the HTML spec was clarified here.

(The spec for `BroadcastChannel` appears to leave `source` unset for messages.)

**Comment by mattto** [comment] 2015-02-18 00:24
Tracked at https://code.google.com/p/chromium/issues/detail?id=459413 for Blink.

**Comment by annevk** [comment] 2015-02-18 08:04
It doesn't really sit well with me that there's a lack of consistency in how service workers are exposed to clients vs how clients are exposed to service workers.

An alternative I proposed was that we make them all live (rather than just one side), updates based on events, and let the message events bubble up to `navigator.serviceWorker` and `self.clients` to make usage a bit easier.

**Comment by jakearchibald** [comment] 2015-02-18 18:00
Code like https://github.com/slightlyoff/ServiceWorker/issues/588#issuecomment-66985639 becomes unworkable if we start putting values behind promises.

```js
and let the message events bubble up to `navigator.serviceWorker`
```

From where? SW instances aside from the one controlling the document are behind promises.

**Comment by jakearchibald** [comment] 2015-02-18 18:33
@mounirlamouri Anne is suggesting the client objects should be 'live'. We can't put their state properties behind promises, else iterating over them to find which client to focus becomes unmanageable. Having client properties update live sounds like a performance issue to me, or is it not as bad as I think?

We could make the values update lazily, making only rough guarantees about accuracy.

Or we could stick with the snapshots and give clients an `id` for comparison purposes.

**Comment by jakearchibald** [comment] 2015-02-18 18:37
Additionally, I think we should make `postMessage` return a promise which rejects on unsuccessful delivery. After a push message, a SW may find a focused & visible client and post a message to it, but that fails because the tab as since been closed. Developers should be able to catch that case and show a notification instead.

This also allows us to reject posts to "asleep" tabs. https://github.com/slightlyoff/ServiceWorker/issues/626

**Comment by annevk** [comment] 2015-02-18 18:44
> Code like #588 (comment) becomes unworkable if we start putting values behind promises.

I was suggesting we keep that live as well, updating based on tasks.

> From where? SW instances aside from the one controlling the document are behind promises.

How does that work if they are live?

**Comment by mounirlamouri** [comment] 2015-02-21 12:58
Making the clients live is going to have a lot of implications on the current design. .focus() would no longer return a new Client object because it wouldn't really make sense. Also, implementations will have to keep track of window objects that are clients and update the service workers that know about them - which, as you pointed - might be a performance issue.

Also, with Chrome shipping the current status of the specification, going backward might come with its share of compat issues.

**Comment by annevk** [comment] 2015-02-23 09:33
Well, the problem is that currently there's not much design to speak of. E.g. elsewhere @jakearchibald argues how useful it is to `===` `ServiceWorker` instances, the same obviously goes for `Client` instances on the other side.

**Comment by jakearchibald** [comment] 2015-02-24 11:18
@annevk @slightlyoff & I had a meeting last night about this stuff. The conclusions were:

* Client & ServiceWorker objects should have an ID (#634 & #635)
* It's ok for `Client` to remain a snapshot, even if `ServiceWorker` becomes live, given the difference in environments
* `serviceWorkerInstance.postMessage` lands at `self.onmessage` within the ServiceWorker. The `messageEvent.source` will be an instance of `WindowClient` or `Client` depending on the sender
* `clientInstance.postMessage` will land at `navigator.serviceWorker.onmessage`. The `messageEvent.source` will be an instance of `ServiceWorker` representing the sender.

The `postMessage` stuff will need to be specced more like `BroadcastChannel` than ports, since they're not 1:1.

**Comment by jakearchibald** [comment] 2015-02-24 11:20
@inexorabletash 

> Just to inform implementation, do we have thoughts (to pass on to @Hixie) about updating the IDL definition for `MessageEvent`'s `source`?

I think we will have to subclass or create our own event type for this.

**Comment by annevk** [comment] 2015-02-24 12:13
I think the `postMessage()` stuff is 1:1 in a way, but the mechanics are different. There's no way to reach more than one service worker or client environment with this setup.

**Comment by annevk** [comment] 2015-02-24 12:15
> I think we will have to subclass or create our own event type for this.

Why not simply get that changed? If @Hixie doesn't deal with the extensibility he could even allow "any" there. Doesn't matter much.

**Comment by catalinb** [comment] 2015-02-25 00:46
@jakearchibald 
>serviceWorkerInstance.postMessage lands at self.onmessage within the ServiceWorker. The >messageEvent.source will be an instance of WindowClient or Client depending on the sender

What about the case when the sender is not controlled by the service worker? Should the source still be an instance of WindowClient/Client?
For example:
```javascript
navigator.serviceWorker.register({some options}).then(function(registration) {
    registration.active.postMessage();
});
```
Assuming the registration has an active worker, the registering window can post messages to the worker without being controlled by it.

**Comment by KenjiBaheux** [comment] 2015-02-25 05:41
@jakearchibald you mentioned that it's desirable to have postmessage return a promise in https://github.com/slightlyoff/ServiceWorker/issues/609#issuecomment-74920652

It's unclear to me if this is indeed part of the consensus reached in https://github.com/slightlyoff/ServiceWorker/issues/609#issuecomment-75739069

**Comment by jungkees** [comment] 2015-02-25 09:45
> What about the case when the sender is not controlled by the service worker? Should the source still be an instance of WindowClient/Client?

I think any instantiated `ServiceWorker` object can postMessage to the service worker represented by it regardless of the state of the service worker and the state it being controlled or not. `registration.installing.postMessage()` should also worker.

Yes, the `event.source` should be an instance of `WindowClient/Client`. Note that `self.clients.matchAll({ includeUncontrolled: true })` resolves with uncontrolled client in the shape of `WindowClient/Client` as well.

**Comment by jungkees** [comment] 2015-02-25 09:48
@jakearchibald In case of the uncontrolled clients gotten from `self.clients.matchAll({ includeUncontrolled: true })`, client.postMessage should still land in the service worker client's global.navigator.serviceWorker.onmessage as long as the ServiceWorkerContainer object exists. Are we on the same page?

**Comment by annevk** [comment] 2015-02-25 10:15
@KenjiBaheux we did not discuss a return value for `postMessage()`. Wouldn't exposing one expose GC? Seems like that might be a bad idea potentially.

**Comment by johnmellor** [comment] 2015-02-25 11:02
@annevk wrote:
> @KenjiBaheux we did not discuss a return value for postMessage(). Wouldn't exposing one expose GC?

Not really, there are many reasons why the postMessage could fail, such as the user having closed the tab, or JS having navigated the tab to a non-same-origin URL.

It's #626 which would arguably expose evicted tabs (which I think is what you refer to by GC).

**Comment by jakearchibald** [comment] 2015-02-25 19:42
I don't think this exposes GC, it's the closing of a window it exposes, and
that seems fine to expose.

**Comment by annevk** [comment] 2015-02-26 08:15
What if the user agent implements "fast back"?

**Comment by jakearchibald** [comment] 2015-02-26 11:31
Good point. But as @johnmellor says, this doesn't give you the difference between a salvageable but unloaded document and a user-closed one, so I don't think it counts as GC exposure.

**Comment by jakearchibald** [comment] 2015-02-26 11:33
@catalinb 

> What about the case when the sender is not controlled by the service worker? Should the source still be an instance of WindowClient/Client?

Yes. You can already get hold of these clients via `clients.getAll({ includeUncontrolled: true })`

**Comment by jakearchibald** [comment] 2015-02-26 11:35
@jungkees 

> In case of the uncontrolled clients gotten from `self.clients.matchAll({ includeUncontrolled: true })`,` client.postMessage` should still land in the service worker client's `global.navigator.serviceWorker.onmessage` as long as the `ServiceWorkerContainer` object exists. Are we on the same page?

Yep! And `global.navigator.serviceWorker` is present in all clients' globals.

**Comment by jungkees** [comment] 2015-02-27 12:16
Spec'ed `ServiceWorker.postMessage()` and `Client.postMessage()`: 6dfce0aacceeef41c813c4680c7f67b96f80c4b6. Just done it in Friday evening and may need to continue the work next week. ;-)

Notes:
  - Now `ServiceWorker` interface is derived from `EventTarget`. (It still implements `AbstractWorker`.) So, the unused `terminate()` method is gone. Implementers: please give me feedback if you have concern about this change.
  - `postMessage` for both directions is specified not by means of `MessagePort` but by queuing a task to the `ServiceWorkerContainer/ServiceWorkerGlobalScope` object directly.

**Comment by Adria2** [comment] 2015-03-06 00:03
I had a hard time following the decision making process to its conclusion here.

Will it be possible to get reference to, and message (unicast not broadcast) the client which originated the fetch event? It's my most important use case.

**Comment by jungkees** [comment] 2015-03-06 01:14
> Will it be possible to get reference to, and message (unicast not broadcast) the client which originated the fetch event? It's my most important use case.

Yes, you can do this:

```js
self.addEventListener("fetch", function(e) {
  e.client.postMessage("To the client initiated this fetch."); 
  // It lands on the client's global object's navigator.serviceWorker.onmessage
});
```

**Comment by jungkees** [comment] 2015-04-10 10:12
Closing.

**Closed by jungkees** 2015-04-10 10:12 UTC
Labels: question
